format = "$all$directory$character"

add_newline = true

[hostname]
ssh_only = true
disabled = true

[username]
disabled = true

[container]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "

[golang]
symbol = "î™ž"

[battery]
disabled = true
